/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_proftabl_proftabl_PB_H_INCLUDED
#define PB_proftabl_proftabl_PB_H_INCLUDED
#include "cs_reticle/bc/pb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _proftabl_Profile {
    char *profile_name;
    char *cartridge_name;
    char *short_name_top;
    char *short_name_bot;
} proftabl_Profile;

typedef struct _proftabl_Payload {
    bool has_profile;
    proftabl_Profile profile;
} proftabl_Payload;

typedef struct _proftabl_ProfileList {
    pb_size_t profile_desc_count;
    struct _proftabl_ProfileListEntry *profile_desc;
    int32_t *activeprofile;
} proftabl_ProfileList;

typedef struct _proftabl_ProfileListEntry {
    char *profile_name;
    char *cartridge_name;
    char *short_name_top;
    char *short_name_bot;
    char *file_path;
} proftabl_ProfileListEntry;


extern proftabl_ProfileList list_msg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define proftabl_Payload_init_default            {false, proftabl_Profile_init_default}
#define proftabl_Profile_init_default            {NULL, NULL, NULL, NULL}
#define proftabl_ProfileList_init_default        {0, NULL, NULL}
#define proftabl_ProfileListEntry_init_default   {NULL, NULL, NULL, NULL, NULL}
#define proftabl_Payload_init_zero               {false, proftabl_Profile_init_zero}
#define proftabl_Profile_init_zero               {NULL, NULL, NULL, NULL}
#define proftabl_ProfileList_init_zero           {0, NULL, NULL}
#define proftabl_ProfileListEntry_init_zero      {NULL, NULL, NULL, NULL, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define proftabl_Profile_profile_name_tag        1
#define proftabl_Profile_cartridge_name_tag      2
#define proftabl_Profile_short_name_top_tag      4
#define proftabl_Profile_short_name_bot_tag      5
#define proftabl_Payload_profile_tag             1
#define proftabl_ProfileList_profile_desc_tag    1
#define proftabl_ProfileList_activeprofile_tag   2
#define proftabl_ProfileListEntry_profile_name_tag 1
#define proftabl_ProfileListEntry_cartridge_name_tag 2
#define proftabl_ProfileListEntry_short_name_top_tag 3
#define proftabl_ProfileListEntry_short_name_bot_tag 4
#define proftabl_ProfileListEntry_file_path_tag  5

/* Struct field encoding specification for nanopb */
#define proftabl_Payload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  profile,           1)
#define proftabl_Payload_CALLBACK NULL
#define proftabl_Payload_DEFAULT NULL
#define proftabl_Payload_profile_MSGTYPE proftabl_Profile

#define proftabl_Profile_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   profile_name,      1) \
X(a, POINTER,  SINGULAR, STRING,   cartridge_name,    2) \
X(a, POINTER,  SINGULAR, STRING,   short_name_top,    4) \
X(a, POINTER,  SINGULAR, STRING,   short_name_bot,    5)
#define proftabl_Profile_CALLBACK NULL
#define proftabl_Profile_DEFAULT NULL

#define proftabl_ProfileList_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  profile_desc,      1) \
X(a, POINTER,  SINGULAR, INT32,    activeprofile,     2)
#define proftabl_ProfileList_CALLBACK NULL
#define proftabl_ProfileList_DEFAULT NULL
#define proftabl_ProfileList_profile_desc_MSGTYPE proftabl_ProfileListEntry

#define proftabl_ProfileListEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   profile_name,      1) \
X(a, POINTER,  SINGULAR, STRING,   cartridge_name,    2) \
X(a, POINTER,  SINGULAR, STRING,   short_name_top,    3) \
X(a, POINTER,  SINGULAR, STRING,   short_name_bot,    4) \
X(a, POINTER,  SINGULAR, STRING,   file_path,         5)
#define proftabl_ProfileListEntry_CALLBACK NULL
#define proftabl_ProfileListEntry_DEFAULT NULL

extern const pb_msgdesc_t proftabl_Payload_msg;
extern const pb_msgdesc_t proftabl_Profile_msg;
extern const pb_msgdesc_t proftabl_ProfileList_msg;
extern const pb_msgdesc_t proftabl_ProfileListEntry_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define proftabl_Payload_fields &proftabl_Payload_msg
#define proftabl_Profile_fields &proftabl_Profile_msg
#define proftabl_ProfileList_fields &proftabl_ProfileList_msg
#define proftabl_ProfileListEntry_fields &proftabl_ProfileListEntry_msg

/* Maximum encoded size of messages (where known) */
/* proftabl_Payload_size depends on runtime parameters */
/* proftabl_Profile_size depends on runtime parameters */
/* proftabl_ProfileList_size depends on runtime parameters */
/* proftabl_ProfileListEntry_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
