/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "proftabl.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(proftabl_Payload, proftabl_Payload, AUTO)


PB_BIND(proftabl_Profile, proftabl_Profile, AUTO)


PB_BIND(proftabl_ProfileList, proftabl_ProfileList, AUTO)


PB_BIND(proftabl_ProfileListEntry, proftabl_ProfileListEntry, AUTO)



